-- Tasks table
CREATE TABLE IF NOT EXISTS Tasks (
    Id SERIAL PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Description TEXT,
    CategoryId INTEGER REFERENCES Categories(Id) ON DELETE SET NULL,
    Priority INTEGER NOT NULL DEFAULT 0 CHECK (Priority IN (0, 1, 2)),
    DueDate TIMESTAMP NOT NULL,
    Status INTEGER NOT NULL DEFAULT 0 CHECK (Status IN (0, 1, 2)),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)